### ISSUE TITLE
Can't add a TrafficManager component to empty

### ISSUE THREAD

**Issue by LouisvanAmerongen** [fcl-engaging-mobility/UnityScripts#6]
When I try to add a traffic component to an empty the script can't be found. When I add Assets/Scripts/Traffic/TrafficManager.cs manual to an empty the the message:
"Please fix compile errors before creating new scripts component". 
A screenshot of the errors is attached to this isseu:
 
![errors vissim script](https://user-images.githubusercontent.com/45392060/50340876-ffc78600-051c-11e9-88e3-7af12fa6d702.JPG)

Unity version:
2018.3.0f2

Platform:
Windows X86

**Comment by mjoos-eth** [comment]
These scripts were developed with Unity 5 and you are using a much newer version of Unity 2018.3. In order to fix those errors with your version, please go to Edit -> Project Settings -> Player -> Other Settings -> Configuration and make sure you have the following settings:

![image](https://user-images.githubusercontent.com/18319304/50578545-7433ea80-0e76-11e9-8d74-10f4e02aedd1.png)

or

![image](https://user-images.githubusercontent.com/18319304/50578563-9594d680-0e76-11e9-93e1-ec9746b0cd0a.png)

You may also need to open AxiomSerialInterpreter.cs and change all:
`case AxiomSerialController.identificationNumber *2`
with
`case 2 * AxiomSerialController.identificationNumber`
